FROM node:23.11.0-bullseye

WORKDIR /app

ENV CHOKIDAR_USEPOLLING=true
# Copy package files and install dependencies
COPY package.json package-lock.json ./

RUN npm ci

COPY . .

CMD ["npm", "run", "dev", "--", "--host=0.0.0.0"]
