
services:

  client:

    container_name: ygp-client-dev
    build:
      context: ./Frontend
      dockerfile: Dockerfile.dev

    ports:
      - 3000:3000
    environment:
      - VITE_API_URL=${DEV___VITE_API_URL}
      - VITE_API_NODE_ENV=${DEV___VITE_API_NODE_ENV}
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./Frontend:/app
      - client-dev-node-modules:/app/node_modules

    restart: unless-stopped
    stdin_open: true # keeps the container running and allows for better terminal interaction
    tty: true
    

  server:
    container_name: ygp-server-dev
    build:
      context: ./Backend
      dockerfile: Dockerfile.dev
    environment:
        - PORT=${DEV___PORT}
        - JWT_ACCESS_SECRET=${DEV___JWT_ACCESS_SECRET}
        - JWT_REFRESH_SECRET=${DEV___JWT_REFRESH_SECRET}
        - ENVIOREMENT=${DEV___ENVIOREMENT}
        - NODE_ENV=${DEV___NODE_ENV}
        - FRONT_URL=${DEV___FRONT_URL}
        - MONGO_INITDB_ROOT_USERNAME=${DEV___MONGO_INITDB_ROOT_USERNAME}
        - MONGO_INITDB_ROOT_PASSWORD=${DEV___MONGO_INITDB_ROOT_PASSWORD}
        - MONGO_INITDB_DATABASE=${DEV___MONGO_INITDB_DATABASE}
        - BUCKET_NAME=${DEV___BUCKET_NAME}
        - BUCKET_REGION=${DEV___BUCKET_REGION}
        - BUCKET_ACCESS_KEY=${DEV___BUCKET_ACCESS_KEY}
        - BUCKET_SECRET_ACCESS_KEY=${DEV___BUCKET_SECRET_ACCESS_KEY}
        - CDN_DOMAIN=${DEV___CDN_DOMAIN}
        - CDN_PUBLIC_KEY_ID=${DEV___CDN_PUBLIC_KEY_ID}
        - CDN_PRIVATE_KEY=${DEV___CDN_PRIVATE_KEY}       
        - EMAIL_HOST=${DEV___EMAIL_HOST}
        - EMAIL_PORT=${DEV___EMAIL_PORT}
        - EMAIL_SECURE=${DEV___EMAIL_SECURE}
        - EMAIL_USER=${DEV___EMAIL_USER}
        - EMAIL_PASS=${DEV___EMAIL_PASS}
  
    ports:
      - 5000:5000
    volumes:
      - ./Backend:/app
      - server-dev-node-modules:/app/node_modules
    env_file:
      - ./Backend/.env

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

    restart: unless-stopped

  mongo:
    container_name: mongo-dev
    image: mongo:latest
    volumes:
      - mongo-dev-data:/data/db
    env_file:
      - ./Backend/.env

    command: mongod --logpath /dev/null  # For no logs at all

    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    restart: unless-stopped
  

volumes:
  client-dev-node-modules:
  server-dev-node-modules:
  mongo-dev-data:


