
services:

  client:

    container_name: ygp-client-dev
    build:
      context: ./Frontend
      dockerfile: Dockerfile.dev
      # args:
      #   VITE_API_URL: http://ygp.ae
      #   VITE_API_NODE_ENV: development
    ports:
      - 5173:5173
    env_file:
      - ./Frontend/.env
    volumes:
      - ./Frontend:/app
      - client-node-modules:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true # keeps the container running and allows for better terminal interaction
    tty: true
    

  server:
    container_name: ygp-server-dev
    build:
      context: ./Backend
      dockerfile: Dockerfile.dev
      # args:
      #   - PORT: 5000
      #   - JWT_ACCESS_SECRET: 🔥💀🚀🛸
      #   - JWT_REFRESH_SECRET: mihyar2
      #   - ENVIOREMENT: production
      #   - NODE_ENV: production
      #   - FRONT_URL: http://ygp.ae

    ports:
      - 5000:5000
    volumes:
      - ./Backend:/app
      - server-node-modules:/app/node_modules
    env_file:
      - ./Backend/.env

  mongo:
    container_name: mongo-dev
    image: mongo:latest
    volumes:
      - mongo-dev-data:/data/db
    env_file:
      - ./Backend/.env

volumes:
  client-node-modules:
  server-node-modules:
  mongo-dev-data:


