services:

  proxy:
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

  client:
    volumes: []
    env_file:
      - ./env/client.prod.env

  server:
    volumes: []
    env_file:
      - ./env/server.prod.env

  mongo:
    env_file:
      - ./env/server.prod.env

  #############################
  # CERT
  #############################
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email ${CERTBOT_EMAIL} -d ${CERTBOT_DOMAIN} --agree-tos
    environment:
      - CERTBOT_EMAIL=tigana137@gmail.com
      - CERTBOT_DOMAIN=ygp.ae

volumes:
  # mongo-data-dev:
  mongo-data:
