services:
  proxy:
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"

  client:
    volumes: []
    env_file:
      - ./env/client.prod.env

  server:
    volumes: []
    env_file:
      - ./env/server.prod.env

  mongo:
    env_file:
      - ./env/server.prod.env

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    command: certonly --webroot -w /var/www/certbot --email tigana137@gmail.com -d ygp.ae --agree-tos --non-interactive

volumes:
  mongo-data: