services:
  client:
    volumes:
      - ./Frontend:/app
      - /app/node_modules  # This creates an anonymous volume for node_modules
    
    

  server:
    volumes:
      - ./Backend:/app
      - /app/node_modules  # This creates an anonymous volume for node_modules


  mongo:
    volumes:
      # - mongo-data-dev:/data/db
      - mongo-data:/data/db


volumes:
  # mongo-data-dev:
  mongo-data:
