FROM node:23.11.0-bullseye

WORKDIR /app


# Copy package files and install dependencies
COPY package.json package-lock.json ./

RUN npm ci
RUN npm i nodemon -D
# Copy source code
COPY . .

CMD ["npm", "run", "dev"] 